#pragma once

enum class TokenType: unsigned int {
    INVALID = 0,
    
    SPACE = 1,
    INDENT = 2,
    ENDLINE = 3,
    SEMICOLON = 4,
    COMMENT_BODY = 5,
    COMMENT_ONELINE = 6,
    COMMENT_OPEN = 7,
    COMMENT_CLOSE = 8,
    
    ASSIGNMENT = 9,
    EQUAL = 10,
    PLUS = 11,
    MINUS = 12,
    TIMES = 13,
    DIVIDE = 14,
    MODULO = 15,
    LESS_THAN = 16,
    LESS_OR_EQUAL = 17,
    MORE_THAN = 18,
    MORE_OR_EQUAL = 19,
    SQUARE_BRACKET_OPEN = 20,
    SQUARE_BRACKET_CLOSE = 21,
    BRACKET_OPEN = 22,
    BRACKET_CLOSE = 23,
    COLON = 24,
    DOT = 25,
    COMMA = 26,
    ROUTINE_ARROW = 27,

    // Keywords
    True,
    False,
    Routine,
    Is,
    Print,
    Var,
    If,
    Else,
    While,
    For,
    Loop,
    Reverse,
    And,
    Or,
    Xor,
    Array,
    Record,
    End,
    IntegerType,
    RealType,
    BooleanType,

    Identifier = 99,

    // Types
    IntLiteral = 100,
    RealLiteral = 101,
    BoolLiteral = 102,
};