#pragma once

enum class TokenType: unsigned int {
    INVALID = 0,
    
    SPACE = 1,
    INDENT = 2,
    ENDLINE = 3,
    SEMICOLON = 4,
    COMMENT_BODY = 5,
    COMMENT_ONELINE = 6,
    COMMENT_OPEN = 7,
    COMMENT_CLOSE = 8,
    
    ASSIGNMENT = 9,
    EQUAL = 10,
    UNEQUAL = 11,
    PLUS = 12,
    MINUS = 13,
    TIMES = 14,
    DIVIDE = 15,
    MODULO = 16,
    LESS_THAN = 17,
    LESS_OR_EQUAL = 18,
    MORE_THAN = 19,
    MORE_OR_EQUAL = 20,
    SQUARE_BRACKET_OPEN = 21,
    SQUARE_BRACKET_CLOSE = 22,
    BRACKET_OPEN = 23,
    BRACKET_CLOSE = 24,
    COLON = 25,
    DOT = 26,
    COMMA = 27,
    ROUTINE_ARROW = 28,

    // Keywords
    True,
    False,
    Routine,
    Is,
    Print,
    Var,
    If,
    Else,
    While,
    For,
    Loop,
    Reverse,
    And,
    Or,
    Xor,
    Array,
    Record,
    End,
    IntegerType,
    RealType,
    BooleanType,

    Identifier = 99,

    // Types
    IntLiteral = 100,
    RealLiteral = 101,
    BoolLiteral = 102,
};